FROM node:22-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --registry=https://registry.npmmirror.com
COPY . .
RUN npx hardhat compile
CMD npx hardhat run scripts/deploy.js --network localhost
